In [1]:
import pandas as pd

data = {'name' : [ 'Jerry', 'Riah', 'Paul'],
        'algol' : [ "A", "A+", "B"],
        'basic' : [ "C", "B", "B+"],
        'c++' : [ "B+", "C", "C+"],
        }

df = pd.DataFrame(data)
df = df.set_index('name')   

df

      algol basic c++
name
Jerry     A     C  B+
Riah     A+     B   C
Paul      B    B+  C+

In [2]:
df.to_csv("./data/df_sample.csv")

In [3]:
df.to_csv("./data/df_sample2.csv", index=False)

In [5]:
#json파일로 저장하기

import pandas as pd

data = {'name' : [ 'Jerry', 'Riah', 'Paul'],
        'algol' : [ "A", "A+", "B"],
        'basic' : [ "C", "B", "B+"],
        'c++' : [ "B+", "C", "C+"],
        }
df = pd.DataFrame(data)
df = df.set_index('name')

df

      algol basic c++
name
Jerry     A     C  B+
Riah     A+     B   C
Paul      B    B+  C+

In [6]:
df.to_json("./data/df_sample.json")

In [7]:
# 엑셀파일로 저장

df

      algol basic c++
name
Jerry     A     C  B+
Riah     A+     B   C
Paul      B    B+  C+

In [9]:
df.to_excel("./data/df_sample2.xlsx",index=False)